Repository Its-Alann/SOEN390-Project-Team8, pull requests merged in 2023-04, with the labels that each got.

#192 Feature/save job
  .gitignore
  cypress/e2e/jobs/BrowseJobs.cy.js
  cypress/e2e/jobs/SavedJobs.cy.js
  cypress/e2e/ui/Navbar.cy.js
  src/App.jsx
  src/Components/Navbar/Navbar.jsx
  src/Pages/Job/BrowseJobs.jsx
  src/Pages/Job/Job.css
  src/Pages/Job/SavedJobs.jsx
Labels: Verified

#193 Redo fix - PFP for network and navbar
  src/Components/Navbar/Navbar.jsx
  src/Components/Network/NetworkCards.jsx
  src/Components/Network/PossibleConnectionCard.jsx
  src/Components/Network/ReceivedInvitationCard.jsx
  src/Components/Network/SentInvitationCard.jsx
Labels: frontend, Low Risk

#194 display stored CV if existing in JobApplication
  src/Pages/Job/JobApplication/JobApplication.jsx
Labels: frontend, backend, Verified
